version: '3.8'
services:
  database:
    build:
      context: ./db
      dockerfile: dockerfile
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "romaav"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - default
  web:
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
    networks:
      - default
    depends_on:
      - database  # Añadido para asegurar que el servicio database esté disponible antes de iniciar web
  adminphp:
    build:
      context: ./php
      dockerfile: dockerfile
    ports:
      - 8000:80
    environment:
      MYSQL_DATABASE: "romaav"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - default
    depends_on:
      - database  # Añadido para asegurar que el servicio database esté disponible antes de iniciar adminphp
networks:
  default:
